### ISSUE TITLE
Case Sensitivity Typo

### ISSUE THREAD

**Issue by delp** [relativty/Relativ#17]
Ran into a problem today where a user running a non-Due arduino wanted to use this option from the code block. But this won't compile unless "Relativ" is changed to "relativ"

Going to do a pull request.

EDIT: I thought I opened this from a specific line but sorry, I am new to this feature.

**Comment by delp** [comment]
Fix here: https://github.com/relativty/Relativ/pull/18

**Comment by maxime-coutte** [comment]
I see, great! Thanks ! :)

**Comment by maxime-coutte** [comment]
I just merged the pull request, feel free to re open if needed :-)
