### ISSUE TITLE
Diopter enhancement

### ISSUE THREAD

**Issue by tutle** [relativty/Relativ#22]
I'm really very exited to build one, do you think it's easy to modify the structure to add dioptry adjustment ?
Really thanks for this amazing job.

**Comment by delp** [comment]
You can try editing the .STL files directly. Or, if you have any experience with 3D modeling, the shape of the headset is easily replaceable by something of your own design, and you can keep the electronics and firmware. If you come up with something like the aforementioned, please fork the repo! Sounds great.

**Comment by AdmiraalHugo** [comment]
There have been added 2 new 3D moddels for the headset by the community. Both of them have options for adjustments.
