### ISSUE TITLE
Hand controls ?

### ISSUE THREAD

**Issue by jmaris** [relativty/Relativ#24]
Hey guys,

Do you have any suggestions for hand based controls (vive style ?)

Thanks

**Comment by delp** [comment]
I think that second hand Wiimote's would be a great choice for this. Low cost (I see them for $5 all the time) and they already have open source libraries.

**Comment by jmaris** [comment]
Cool ! Merci beaucoup :) et franchement je suis vraiment impressionné par votre travail (et le niveau d'anglais ;) )  Bon continuation!
